class Filter:
    warning = ["WRN/CCS/AaTestPort, CTcpConnect_Destroy",
               "WRN/CCS/AaSysComGw, Could not find route with ID",
               "WRN/CCS/AaSysComGwRoute, removeRoute: No route with",
               "StartUpProcess WRN/Srio",
               "WRN/CCS/CCSDaemon, CcsStartupApplications: Parse application definition file error",
               "WRN/HWA/RESET, Failed to read reset type and reset cause from FPGA/Supervisor",
               "WRN/CCS/AaTestPort, AaTestPortServerPhantomStart:Phantom port Cpid after registration",
               "WRN/CCS/AaError",
               "WRN/CCS/AaSysComUser, Implicit creation of message queue performed",
               "WRN/CCS/AaSysCom, Message send failed",
               "WRN/CCS/AaSysInfo, validateConfiguration: OUT failed",
               "WRN/CCS/AaPostmortem, Not recognized event parameter",
               "WRN/HWA/SFP",
               "WRN/HWA/HWASYNC, [refmon] Received change notification for not monitored reference clock",
               "BTS_SW/HWRStartupExe",
               "WRN/TRSW/TRSWSyslog",
               "WRN/CCS/AaPostmortem",
               "WRN/SrioDbgFdqStarvFastUpdate: Updating new resources",
               "WRN/HWA/ClimateS, BlackBoxData::createBlackboxFile(): failed to get passive SW version",
               "WRN/CCS/AaSysCom, Hop already exists for destination",
               "WRN/HWA/MLG, Failed to check supervisorTag",
               "WRN/LFS/LinuxSyslog",
               "WRN/CCS/AaSysCom, AaSysComCheckMessagePoolId: use ipc pool instead of dpm pool"]

    error = ["ERR/LFS/LinuxSyslog",
             "ERR/TRSW/TRSWSyslog",
             "INF/CCS/AaError",
             "INF/TRSW/TRSWSyslog",
             "INF/LFS/LinuxSyslog",
             "INF/HWA/PY",
             "ERR/HWA/ClimateS, BlackBoxData::createBlackboxFile(): failed to get active SW version",
             "ERR/CCS/AaError",
             "ERR/EXTLOG/DDAL",
             "StartUpProcess ERR/LTE MAC: No RadioTimeConfigResp received",
             "ERR/CCS/AaFile",
             "StartUpProcess ERR/TestEnv: No RadioTimeConfigResp received",
             "VIP/LFS/LinuxSyslog",
             "ERR/CCS/AaSysLog, processPrintPmGen removing of pmGenerationLogAbsPath",
             "ERR/CCS/AaFile, stdioListDir(): cannot open directory",
             "ERR/HWA/HWATIME",
             "INF/HWA/RESET",
             "ERR/HWA/PowerS",
             "ERR/CCS/AaPro, AaProCmdExecHandleFlags: Command exited",
             "INF/EXTLOG/DDAL",
             "ERR/CCS/AaPro, AaProCmdExitStatusHandleWIFEXITED"]


